networks:
  boursenet:
    driver: bridge

# Add this section to create a named volume
volumes:
  timescaledb_data:

services:
  db:
    image: reg.undercloud.cri.epita.fr/docker/timescale/timescaledb:latest-pg16
    container_name: db
    command: postgres -c shared_preload_libraries=timescaledb
    ports:
      - "5432:5432"
    networks:
      - boursenet
    environment:
      - PGDATA=/var/lib/postgresql/data/timescaledb
      - POSTGRES_DB=bourse
      - POSTGRES_USER=ricou
      - POSTGRES_PASSWORD=monmdp
    volumes:
      # Use a named volume instead of a host-mounted directory
      - timescaledb_data:/var/lib/postgresql/data/timescaledb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ricou -d bourse"]
      interval: 10s
      timeout: 5s
      retries: 5

  etl:
    image: my_etl
    container_name: etl
    depends_on:
      db:
        condition: service_healthy
    networks:
      - boursenet
    volumes:
      - /mnt/c/Users/leolo/OneDrive/Bureau/temp_big_data/data:/home/bourse/data/

  dashboard:
    image: my_dashboard
    container_name: dashboard
    depends_on:
      db:
        condition: service_healthy
    networks:
      - boursenet
    ports:
      - "8050:8050"